server:
  port: 0   # random port

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/caring_user?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: springproject
    driver-class-name: com.mysql.cj.jdbc.Driver
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: msa_user
#    password: test123


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple USER-SERVICE.

management:
  endpoints:
    web:
      exposure:
        include: "*"

token:
  expiration_time: 86400000
  secret: cf0ac9608f0325faf5e8085deb19c8f6e90140354135b0c509988c36b0a2fa11