server:
  port: 0   # random port

spring:
  application:
    name: user-service

greeting:
  message: Welcome to the Simple USER-SERVICE.

management:
  endpoints:
    web:
      exposure:
        include: "*"
